name: petmatch
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  google_sign_in: ^4.5.5
  flutter_secure_storage: ^3.3.4
  geolocator: ^6.1.0
  dio: ^3.0.10
  http:
  share: ^0.6.3+5
  image_picker: ^0.6.3+1
  mime: ^0.9.6+3
  flushbar: ^1.10.4

#  firebase_auth: "^0.5.10"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg.png
    - assets/first.png
    - assets/second.png
    - assets/third.png
    - assets/fourth.png
    - assets/Home.png
    - assets/home2.png
    - assets/chat.png
    - assets/chat2.png
    - assets/account.png
    - assets/account2.png
    - assets/els-fattah.jpg
    - assets/jonathan-daniels.jpg
    - assets/sam-burriss.jpg
    - assets/warren-wong.jpg
    - assets/Background.png
    - assets/sign_up_bg.png
    - assets/back-arrow.png
    - assets/1.jpg
    - assets/img1.png
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/img4.jpg
    - assets/img5.jpg
    - assets/screen.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
